# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

edgeOnLoop <- function(fromNode, toNode, parSet) {
    .Call(`_LRnetST_edgeOnLoop`, fromNode, toNode, parSet)
}

hcSC_ <- function(Y, nodeType, whiteList, blackList, tol = 1e-6, maxStep = 500L, restart = 10L, seed = 1L, verbose = FALSE) {
    .Call(`_LRnetST_hcSC_`, Y, nodeType, whiteList, blackList, tol, maxStep, restart, seed, verbose)
}

