# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

score_shd_freq_cpp <- function(freq, alpha, freqCutoff, whiteList, blackList, verbose = FALSE) {
    .Call(`_LRnetSTv2_score_shd_freq_cpp`, freq, alpha, freqCutoff, whiteList, blackList, verbose)
}

score_shd_cpp <- function(bootAdj, alpha, freqCutoff, whiteList, blackList, verbose = FALSE) {
    .Call(`_LRnetSTv2_score_shd_cpp`, bootAdj, alpha, freqCutoff, whiteList, blackList, verbose)
}

edgeOnLoop <- function(fromNode, toNode, parSet) {
    .Call(`_LRnetSTv2_edgeOnLoop`, fromNode, toNode, parSet)
}

hcSC_ <- function(Y, nodeType, whiteList, blackList, tol = 1e-6, maxStep = 500L, restart = 10L, seed = 1L, verbose = FALSE) {
    .Call(`_LRnetSTv2_hcSC_`, Y, nodeType, whiteList, blackList, tol, maxStep, restart, seed, verbose)
}
